# Setup
title:        Object Oriented Programming
tagline:      This is the page of the Object Oriented Programming course (2017-2)
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Alejandro Velasco
  url:        https://co.linkedin.com/in/sebastian-alejandro-velasco-dimate-226312101

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown